가챠기능 추가
leehj050211/MC-Economy-Plugin pull request #1
Opened 2023-08-21 05:36 UTC by min050410

2023-08-22 14:15 UTC, leehj050211 requested changes
메인 브랜치에서는 gui 관련 코드를 라이브러리로 전부 대체했으니 메인 브랜치 변경사항 pull받고 gui 관련 코드 리팩토링 하시면 되겠습니다!

2023-08-22 14:15 UTC, leehj050211 commented on src/main/java/leehj050211/mceconomy/gui/gacha/GachaGui.java
> +        playerDao.update(playerData);
데이터 저장은 10분마다 혹은 서버가 종료될 때 자동 저장되니까 따로 저장하지 않아도 됩니다.

2023-08-23 07:15 UTC, leehj050211 approved these changes

2023-08-23 07:15 UTC, merged

2023-08-24 05:25 UTC, min050410 commented on src/main/java/leehj050211/mceconomy/gui/gacha/GachaGui.java
> +        playerDao.update(playerData);
그러쿤요